---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cne-deployment
  labels:
    app: devops
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devops
  template:
    metadata:
      labels:
        app: devops
    spec:
      containers:
      - name: devops-cne-demo
        image: devandteach/cne-demo-app:v1.0.0
        ports:
        - containerPort: 80
        

---

apiVersion: v1
kind: Service
metadata:
  name: devops-service
  labels:
    app: devops
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: devops
 
      
      
